name: Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - __NO_EXECUTE__

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: Kesin11/actions-timeline@v2
        if:  ${{ !env.ACT }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: Sotalbireo/mobamastorage-ninomiyaasuka
          token: ${{ secrets.GH_PAT_CLONE_DATA_REPO }}
          path: data

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          check-latest: true
          node-version: 20

      - run: yarn global add vercel@latest

      - run: yarn install

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
